# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-28 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayDiagnose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagepath', models.CharField(db_index=True, max_length=200, verbose_name='图片路径')),
                ('ai_p_dx', models.IntegerField(blank=True, choices=[(0, '无肺炎'), (1, '肺炎'), (2, '不确定')], null=True, verbose_name='AI肺炎标注')),
                ('ai_n_dx', models.IntegerField(blank=True, choices=[(0, '无肺炎'), (1, '肺炎'), (2, '不确定')], null=True, verbose_name='AI肺结核标注')),
                ('raw_p_dx', models.IntegerField(choices=[(0, '无肺炎'), (1, '肺炎'), (2, '不确定')], default=0, verbose_name='原始肺炎标注')),
                ('raw_n_dx', models.IntegerField(choices=[(0, '无肺结核'), (1, '肺结核'), (2, '不确定')], default=0, verbose_name='原始肺结核标注')),
                ('p_dx', models.IntegerField(blank=True, choices=[(0, '无肺炎'), (1, '肺炎'), (2, '不确定')], null=True, verbose_name='医生肺炎标注')),
                ('n_dx', models.IntegerField(blank=True, choices=[(0, '无肺结核'), (1, '肺结核'), (2, '不确定')], null=True, verbose_name='医生肺结核标注')),
                ('dxDate', models.DateTimeField(auto_now=True, verbose_name='标注日期')),
                ('status', models.IntegerField(choices=[(0, '未标注'), (1, '已展示未标注'), (2, '已标注')], default=0, verbose_name='是否标注')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xraw_set', to=settings.AUTH_USER_MODEL, verbose_name='医生用户')),
            ],
        ),
    ]
